### ISSUE TITLE
Rotation and Translation are identity and 0 always

### ISSUE THREAD

**Issue by ashnarayan13** [symao/libicp#2]
Hi,

I was using the point to plane  ICP on 2D data. While the results are correct when I use Eigen::umeyama(), the results I get when I run the IcpPointToPlane gives 
Transformation results:
R:
   1.0000000    0.0000000    0.0000000 
   0.0000000    1.0000000    0.0000000 
   0.0000000    0.0000000    1.0000000 

t:
   0.0000000 
   0.0000000 
   0.0000000 

I am testing it with a simple function y = x² + c on 50 points and 1000 points. 
I just changed the demo.cpp as follows

> int32_t dim = 2;
  int32_t num = 1000;

>  // allocate model and template memory
  double* M = (double*)calloc(dim*num,sizeof(double));
  double* T = (double*)calloc(dim*num,sizeof(double));

>  // set model and template points
  cout << endl << "Creating model with 10000 points ..." << endl;
  cout << "Creating template by shifting model by (1,0.5,-1) ..." << endl;
  int32_t k=0;
  
>  for(int i=0; i<num; i++){
  	M[k * dim+0] = i;
  	M[k * dim+1] = std::pow(i,2);
  	T[k * dim+0] = i;
  	T[k * dim+1] = std::pow(i,2)+10;
  	k++;
  }

  >// start with identity as initial transformation
  // in practice you might want to use some kind of prediction here
  Matrix R = Matrix::eye(dim);
  Matrix t(dim,1);

  >// run point-to-plane ICP (-1 = no outlier threshold)
  cout << endl << "Running ICP (point-to-plane, no outliers)" << endl;
  IcpPointToPlane icp(M,num,dim);
  double residual = icp.fit(T,num,R,t,-1);

I am not sure what I am missing. Eigen::umeyama() gives the correct translation of (0,10) for the 2 curves.

Thanks!

**Comment by symao** [comment]
Hi ashnarayan13, it's a bug at the code below in icpPointToPlane.cpp, where i changed the raw search method from k-nearest to r-nearest and used a fixed r threshold(0.05), thus when you input points with distance over 0.05, the point normal will not be calculated correctly, since it has no neighbor in radius 0.05.
```
double* IcpPointToPlane::computeNormals (const int32_t num_neighbors,const double flatness) {
    double *M_normal = (double*)malloc(m_kd_tree->N*m_dim*sizeof(double));
    kdtree::KDTreeResultVector neighbors;
    for (int32_t i=0; i<m_kd_tree->N; i++) {
      //M_tree->n_nearest_around_point(i,0,num_neighbors,neighbors);
      m_kd_tree->r_nearest_around_point(i,0,0.05,neighbors);
      if (m_dim==2) computeNormal(neighbors,M_normal+i*2,flatness);
      else        computeNormal(neighbors,M_normal+i*3,flatness);
    }
    return M_normal;
 }
```

Just comment 'm_kd_tree->r_nearest_around_point(i,0,0.05,neighbors);' and use n_nearest_around_point(). Or you can checkout the [new commit](https://github.com/symao/libicp/commit/5b9784ed08f63fa607e6e84624f8e0f34b929324) which fixed this bug.

By the way, i found another mistake at fitIterate() in icp.cpp, check [this commit](https://github.com/symao/libicp/commit/c5ac7cca694496a0f2f8b6af7b7c2b6bac170a57) for details.
